### ISSUE TITLE
Can not build firmware successful. and how to build ffp host software for windows?

### ISSUE THREAD

**Issue by Droid-MAX** [adamgreig/ffp#8]
Compiling output below:

error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `stable_deref_trait`.

OS Type:
Linux 4.9.0 Debian 9

Rustc/Cargo Version:
rustc 1.44.0-nightly (94d346360 2020-04-09)
cargo 1.44.0-nightly (390e8f245 2020-04-07)

**Comment by adamgreig** [comment]
It looks like you need the thumbv6m-none-eabi target added, try:

```
rustup target add thumbv6m-none-eabi
```

Thanks for reporting! I've updated the firmware README with more instructions so this should be easier for people in future, too.

**Comment by adamgreig** [comment]
Let me know if that fixed it! For the host software, does `cargo build --release` work? You probably need libusb installed, but I'm afraid I don't know how to set that up on Windows.

**Comment by Droid-MAX** [comment]
firmware build successful! but have no idea about how to set that up on windows too.

**Comment by Droid-MAX** [comment]
I think the installation command of dfu-util package should also be written in README.md

**Comment by Droid-MAX** [comment]
Can you help me test the cross-compiled ffp.exe?

https://github.com/Droid-MAX/ffp/releases/tag/1.2.0-beta

Related files are in this link. 

or you also need zadig.exe to install libusb/winusb drivers for ffp.

**Comment by adamgreig** [comment]
Sorry, I don't have access to any Windows systems so I can't test the EXEs myself. If you could write what is needed for Windows driver installation I'd like to add it to the `driver/README.md` file here though. I think instead of using zadig it should be possible to create a suitable WinUSB driver file specific for the FFP which works with libusb.

By the way, is there a reason your ffp repository is a whole separate repository instead of a fork? No problem, just interested.

**Comment by adamgreig** [comment]
Ok, I was able to get this working in a VM. It actually needed a firmware fix*. I've made some driver files using zadig which I'll add to this repository. Your pre-built ffp.exe works fine:

![image](https://user-images.githubusercontent.com/47219/79076476-5cdae280-7cf2-11ea-9147-056e255382d7.png)

I'll add some instructions to the README.

\* Windows requests a configuration descriptor with length 255 bytes, and the ffp descriptor total is 64 bytes, so a correct reply needs to send a zero-length packet after the 64 bytes. On Linux, the request is made for exactly 64 bytes, so the zero-length packet is not required, so I didn't notice this. It's fixed now.

**Comment by adamgreig** [comment]
Hi @Droid-MAX, I've updated the software to use `rusb` instead of `libusb`, which seems to build on Windows without any other requirement or installation. Hopefully this makes Windows builds easier.

I've also changed the firmware to use WinUSB and Windows OS feature detection so I think zadig should not be needed either, the devices should automatically be recognised and use WinUSB drivers.

**Comment by Droid-MAX** [comment]
It doesn't really matter, don't forget that dfu-util needs zadig in addition to ffp. I suggest keeping the status quo.

**Comment by Droid-MAX** [comment]
after you updated software source code, It failed when I cross-compiled it and prompt miss "poll.h" in mingw env. 
It is recommended to roll back to the previous version of the software. 
libusb1-sys does not consider the case of cross compilation.

**Comment by Droid-MAX** [comment]
latest firmware released:
https://github.com/Droid-MAX/ffp/releases/tag/1.2.0-beta-20200414

**Comment by adamgreig** [comment]
> after you updated software source code, It failed when I cross-compiled it and prompt miss "poll.h" in mingw env.
> It is recommended to roll back to the previous version of the software.
> libusb1-sys does not consider the case of cross compilation.

Hmm, that's annoying. I swapped because `libusb` is 4 years old and not maintained, but `rusb` is a fork that is actively maintained. I believe `libusb1-sys` is also just an updated fork of `libusb-sys`, so they should cross-compile the same. I was able to build ffp.exe successfully on Windows 7 with MSVC using `rusb`, but I can't get either version to cross compile.

How did you cross compile the old version?

**Comment by Droid-MAX** [comment]
Or you release the latest control software, pay attention to distinguish between 32-bit and 64-bit versions.

**Comment by adamgreig** [comment]
Ok, I was able to cross-compile in the end. Here's the full instructions from a totally stock Ubuntu 18.04 image:

```sh
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# (accept defaults)
$ source $HOME/.cargo/env
$ cd /tmp
$ rustup target add x86_64-pc-windows-gnu
$ apt install -y p7zip-full build-essential gcc-mingw-w64-x86-64 libusb-1.0 pkg-config
$ wget https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z
$ 7z x libusb-1.0.23.7z
$ git clone https://github.com/adamgreig/ffp
$ cd ffp/software
$ mkdir .cargo
$ echo -e '[target.x86_64-pc-windows-gnu]\nlinker = "x86_64-w64-mingw32-gcc"\nrustflags = [ "-L", "/tmp/MinGW64/dll/"]' > .cargo/config
$ env PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --target x86_64-pc-windows-gnu
```

Resulting binary is `target/x86_64-pc-windows-gnu/release/ffp.exe`, and I tested it on a Windows 7 (x64) VM. It needs the `libusb-1.0.dll` file available on the Windows system, either in the same directory as `ffp.exe` or installed system-wide. I think this should work for 32-bit too if you change the relevant targets and use the 32-bit `libusb-1.0.dll`.

This is encouraging so I plan to set up automatic build of software for Windows and Linux via CI sometime, but I'm not sure when.

**Comment by adamgreig** [comment]
I think that answers this issue, so I'll close this one now, but please respond if you have any questions or open new issues for any other problems.

Thank you for encouraging me to investigate Windows builds, I'm glad it can be done and now supports Windows!

I would be interested to know if the latest firmware still requires zadig WinUSB drivers installed on Windows, or if it just works out of the box now. As far as I can tell, I'm doing everything right for WinUSB drivers to activate.

**Comment by Droid-MAX** [comment]
I also think that the CI system should be used to complete the compilation automatically.
Maybe you can consider the Github Action function?

**Comment by adamgreig** [comment]
@Droid-MAX, releases now have pre-built windows executables and firmware images: https://github.com/adamgreig/ffp/releases/tag/v1.3.0
